Name:           ros-indigo-aubo-new-driver
Version:        0.3.15
Release:        0%{?dist}
Summary:        ROS aubo_new_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/aubo_new_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-actionlib
Requires:       ros-indigo-aubo-description
Requires:       ros-indigo-aubo-msgs
Requires:       ros-indigo-control-msgs
Requires:       ros-indigo-controller-manager
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-hardware-interface
Requires:       ros-indigo-ros-controllers
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-rospy
Requires:       ros-indigo-sensor-msgs
Requires:       ros-indigo-std-msgs
Requires:       ros-indigo-tf
Requires:       ros-indigo-trajectory-msgs
BuildRequires:  ros-indigo-actionlib
BuildRequires:  ros-indigo-aubo-msgs
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-control-msgs
BuildRequires:  ros-indigo-controller-manager
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-hardware-interface
BuildRequires:  ros-indigo-message-generation
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-sensor-msgs
BuildRequires:  ros-indigo-std-msgs
BuildRequires:  ros-indigo-tf
BuildRequires:  ros-indigo-trajectory-msgs

%description
The aubo_new_driver package for AUBO-I5 connect the TCP/IP Server

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Mar 31 2017 liuxin <liuxin@our-robotics.com> - 0.3.15-0
- Autogenerated by Bloom

* Thu Nov 24 2016 liuxin <liuxin@our-robotics.com> - 0.3.12-1
- Autogenerated by Bloom

* Thu Nov 24 2016 liuxin <liuxin@our-robotics.com> - 0.3.12-0
- Autogenerated by Bloom

* Mon Nov 21 2016 liuxin <liuxin@our-robotics.com> - 0.3.7-0
- Autogenerated by Bloom

* Mon Nov 21 2016 liuxin <liuxin@our-robotics.com> - 0.3.6-1
- Autogenerated by Bloom

* Thu Nov 17 2016 liuxin <liuxin@our-robotics.com> - 0.3.6-0
- Autogenerated by Bloom

* Wed Nov 16 2016 liuxin <liuxin@our-robotics.com> - 0.3.4-0
- Autogenerated by Bloom

* Wed Nov 16 2016 liuxin <liuxin@our-robotics.com> - 0.3.2-0
- Autogenerated by Bloom

