Name:           ros-kinetic-aubo-robot
Version:        0.3.18
Release:        0%{?dist}
Summary:        ROS aubo_robot package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-aubo-control
Requires:       ros-kinetic-aubo-description
Requires:       ros-kinetic-aubo-driver
Requires:       ros-kinetic-aubo-gazebo
Requires:       ros-kinetic-aubo-i5-moveit-config
Requires:       ros-kinetic-aubo-kinematics
Requires:       ros-kinetic-aubo-msgs
Requires:       ros-kinetic-aubo-new-driver
Requires:       ros-kinetic-aubo-panel
Requires:       ros-kinetic-aubo-trajectory
Requires:       ros-kinetic-aubo-trajectory-filters
BuildRequires:  ros-kinetic-catkin

%description
Description,drivers, moveit and utilities for AUBO Robot Arms.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Sep 05 2017 liuxin <liuxin@our-robotics.com> - 0.3.18-0
- Autogenerated by Bloom

