Name:           ros-jade-aubo-new-driver
Version:        0.3.10
Release:        1%{?dist}
Summary:        ROS aubo_new_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/aubo_new_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-actionlib
Requires:       ros-jade-aubo-description
Requires:       ros-jade-aubo-msgs
Requires:       ros-jade-control-msgs
Requires:       ros-jade-controller-manager
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-hardware-interface
Requires:       ros-jade-ros-controllers
Requires:       ros-jade-roscpp
Requires:       ros-jade-rospy
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-std-msgs
Requires:       ros-jade-tf
Requires:       ros-jade-trajectory-msgs
BuildRequires:  ros-jade-actionlib
BuildRequires:  ros-jade-aubo-msgs
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-control-msgs
BuildRequires:  ros-jade-controller-manager
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-hardware-interface
BuildRequires:  ros-jade-message-generation
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-tf
BuildRequires:  ros-jade-trajectory-msgs

%description
The aubo_new_driver package for AUBO-I5 connect the TCP/IP Server

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Thu Nov 24 2016 liuxin <liuxin@our-robotics.com> - 0.3.10-1
- Autogenerated by Bloom

* Thu Nov 24 2016 liuxin <liuxin@our-robotics.com> - 0.3.10-0
- Autogenerated by Bloom

